name: Run diKTat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diktat_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Cache local Gradle repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run diktat itself via ktlint
        run: ./gradlew diktatCheck -Pdiktat.githubActions=true
      - name: Upload SARIF report to Github
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: build/reports/diktat
