name: Run diKTat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diktat_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Run diktat
        uses: gradle/gradle-build-action@v2
        with:
          args: |
            diktatCheck
            -Pdiktat.githubActions=true
            --build-cache
      - name: Upload SARIF report to Github
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: build/reports/diktat
